#!/bin/sh

if ! ( netstat -an | grep -qs ':9160' ); then
    echo "You need to create an SSH tunnel to Cassandra to run these tests."
    echo "Example: juju ssh e-t-cassandra/0 -N -L -9160:external.ip.addr:9160"
    exit 1
fi

for path in test/test_*.py; do
    PYTHONPATH=. python $path
done
