#!/bin/sh
set -e

OUT="$(./create_instance init_cassandra.sh medium | tee /dev/fd/2 )"
CASSANDRA_IP="$(echo "$OUT" | grep "Instance available:" | cut -d' ' -f3)"
CASSANDRA_ID="$(echo "$OUT" | grep "Instance started:" | cut -d' ' -f3)"

OUT="$(./create_instance init_rabbitmq.sh medium | tee /dev/fd/2 )"
RABBIT_IP="$(echo "$OUT" | grep "Instance available:" | cut -d' ' -f3)"
RABBIT_ID="$(echo "$OUT" | grep "Instance started:" | cut -d' ' -f3)"
if [ -n "$CASSANDRA_IP" ] && [ -n "$RABBIT_IP" ]; then
    # Sigh. euca2ools doesn't like <(cat foo; cat foo)
    WORKING=$(mktemp)
    cat init_webserver.sh > $WORKING
    echo "sed -i 's,cassandra_host = .*,cassandra_host = \"$CASSANDRA_IP\",'" \
        " /var/www/whoopsie-daisy/backend/configuration.py" >> $WORKING
    echo "sed -i 's,amqp_host = .*,amqp_host = \"$RABBIT_IP\",'" \
        " /var/www/whoopsie-daisy/backend/configuration.py" >> $WORKING
    OUT="$(./create_instance $WORKING medium | tee /dev/fd/2 )" || \
        euca-terminate-instances $CASSANDRA_ID $RABBIT_ID
    rm $WORKING
fi
