#!/bin/sh

START_PORT=9160
PIDS=

NODES='jumbee.canonical.com
tomte.canonical.com
nawao.canonical.com
laelaps.internal
geryon.internal
nargun.internal'

cleanup () {
    for pid in $PIDS; do
        echo "Killing $pid."
        kill $pid || :
    done
    exit 0
}
trap cleanup INT TERM EXIT

for node in $NODES; do
    hostname="$(ssh cassandra@${node} hostname -I | tr -d '\n' | tr -d ' ')"
    if [ $? != 0 ] || [ -z "$hostname" ]; then
        echo "Could not establish connection to ${node}."
        continue
    fi
    ssh cassandra@${node} -L ${START_PORT}:${hostname}:9160 -N &
    PIDS="${PIDS} $!"
    echo "Connection established to $node on $START_PORT."
    START_PORT=$((START_PORT + 1))
done

sleep inf
